Repository Ureka-Momo-s-friends/Frontend, pull requests merged in 2024-11, with the labels that each got.

#9 Feature/cam
  public/img/cam-button.png
  src/components/Map/Cam.jsx
  src/images/avatar_profile.png
  src/pages/map/MapPage.jsx
Labels: ✨ Feature

#17 Map page
  src/pages/map/MapPage.jsx
Labels: 🎨 Html&css

#18 Profile
  src/components/Profile/ProfileContent/ProfileTitle.jsx
  src/components/Profile/ProfileHeader/Header.css
  src/components/Profile/ProfileHeader/Header.jsx
  src/components/Profile/ProfileUpdate/ProfilePetUpdate.jsx
  src/components/Profile/ProfileUpdate/ProfileUpdate.jsx
  src/components/Profile/style.js
  src/pages/Pay/PaymentHistory.jsx
  src/pages/Profile/ProfileLayout.jsx
  src/pages/Profile/ProfilePage.jsx
  src/pages/Profile/ProfilePetUpdatePage.jsx
  src/pages/Profile/ProfileUpdatePage.jsx
Labels: 🎨 Html&css, 🔨 Refactor

#20 Feature/order detail
  src/Router.js
  src/components/Profile/ProfileContent/ProfileContent.jsx
  src/components/Profile/ProfileUpdate/ProfilePetUpdate.jsx
  src/components/Profile/style.js
  src/pages/Pay/OrderDetailPage.jsx
  src/pages/Pay/PaymentHistory.jsx
  src/pages/Pay/style.js
  src/pages/index.js
  src/pages/map/MapPage.jsx
  src/styles/GlobalStyle.js
Labels: 🐞 Bug, 🎨 Html&css
