Repository Ureka-Momo-s-friends/Frontend, pull requests merged in 2024-10, with the labels that each got.

#2 [#1] 프로젝트 세팅
  .eslintrc
  .gitignore
  .prettierrc
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/App.test.js
  src/Router.js
  src/index.js
  src/pages/index.js
  src/pages/main/HomePage.jsx
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/GlobalStyle.js
  src/utils/recoilAtom.js
Labels: ⚙ Setting

#3 Login
  package-lock.json
  package.json
  src/index.js
  src/pages/KakaoLogin.jsx
  src/pages/Login.jsx
  src/pages/main/HomePage.jsx
Labels: ✨ Feature

#4 Mainpage
  .eslintrc
  jsconfig.json
  package-lock.json
  package.json
  public/img/banner/banner1.JPG
  public/img/banner/banner2.JPG
  public/img/banner/banner3.JPG
  public/img/banner/banner4.JPG
  public/img/banner/banner5.JPG
  public/img/categoryimg/cateitem.png
  public/img/categoryimg/cateitem2.png
  public/img/categoryimg/cateitem3.png
  public/img/categoryimg/cateitem4.png
  public/img/categoryimg/cateitem5.png
  public/img/categoryimg/cateitem6.png
  public/img/mm.png
  public/img/mm2.jpg
  public/img/mm3.jpg
  public/index.html
  src/assets/svgs/CartIcon.svg
  src/assets/svgs/CatIcon.svg
  src/assets/svgs/HomeIcon.svg
  src/assets/svgs/SearchIcon.svg
  src/assets/svgs/UserIcon.svg
  src/assets/svgs/index.js
  src/components/Main/Bottombar/index.jsx
  src/components/Main/Bottombar/style.js
  src/components/Main/Header/index.jsx
  src/components/Main/Header/style.js
  src/components/Main/MainContents/index.jsx
  src/components/Main/MainContents/style.js
  src/pages/main/HomePage.jsx
  webpack.config.js
Labels: 🎨 Html&css

#8 Map page
  package.json
  src/pages/map/MapPage.jsx
Labels: 🎨 Html&css, 📃 Docs
